### ISSUE TITLE
target queryselector string not working

### ISSUE THREAD

**Issue by zbug** [martinsuba/iframe-manager#4]
Hi,

I noticed, that the target is not working as I expected it to be. 

HTML: 

```
<!DOCTYPE html>
<html>
<head></head>
<body id="content">
    <div id="iFrameContainer1"></div>
    <script src="src/main.js"></script>
</body>
</html>
```

When using '#iFrameContainer1' as target for the injected iFrame, I end up with 
```
<!DOCTYPE html>
<html>
<head></head>
<body id="content">
    <div id="iFrameContainer1"></div>
    <script src="src/main.js"></script>
     <iframe... />
</body>
</html>
```

Best

**Comment by zbug** [comment]
Nevermind ... the error was caused during my inject. I used an invalid variable name during this object instantiation: 
 iFrame.injectedIframe = iframeManager.inject({
        source: iFrame.source,
        style,
        attributes,
        selector // should have been "target"
    });


Unfortunately, your error code does not work:
end of "inject" method: 
`if(null==u)throw new Error("Cannot find target element in the DOM.");`
=> this check is never null as u will be your body in case of an invalid querySelector string

**Comment by martinsuba** [comment]
@zbug thanks for the comment. I think the error code works fine, but you didn't specified the  `target` selector, so the default fallback is document.body (it's in the README file). The error is thrown when you specify some string selector and this selector couldn't be found in the DOM.
